version: '3'

services:
  web:
    build: .
    command: yarn start
    volumes:
        - .:/short_url
        - /short_url/node_modules
    ports:
      - 8080:8080
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: "redis:3-alpine"
